In [11]:
import pandas as pd
import requests
import pdfplumber

In [12]:
pdf_path = "anual.pdf"

In [13]:
data = []

with pdfplumber.open(pdf_path) as pdf:
    for i, page in enumerate(pdf.pages):
        text = page.extract_text()
        data.append({"page_number": i, "text": text})

data


[{'page_number': 0,
  'text': '2022 - 23\nवा\x00ष\x00क \x00\x00तवेदन\nAnnual Report\nआईआईआईट\x00 रायचूर\nIIIT Raichur'},
 {'page_number': 1,
  'text': 'पृ\x00/ Page 2\nWinning Entry: Eco-Friendly\nGanesha Idol (2023)\nby: Harika, Sowmya,\nDeepthika,Pavithra,Poojitha Photo Credit: Ashish Arya\nवा\x00षक \x00\ufff8तवेदन/ Annual Report | 2022-23'},
 {'page_number': 2,
  'text': "पृ\x00/ Page 3\n/ Contents\nअनु\x00म\x00णका\n4-5 प\x00रचय / Introduction\n6 11 \x00नदेशक IIIT रायचूर क\x00 \x00रपोट\x00 /Report of Director IIIT Raichur\n12-13 माग\x00दश\x00क \x00नदेशक का संदेश / Mentor Director's Message\n14-15 शै\x00\x00क काय\x00\x00म /Offerings\n16-18 शासक मंडल/ Board of Governors\n19-20 \x00व\x00 स\x00म\x00त/ Finance Committee\n21-22 सम\x00वय स\x00म\x00त/ Coordination Committee\n23-24 \x00श\x00ा-प\x00रषद/ Senate\n25-27 आईआईआईट\x00 रायचूर संकाय/ IIIT RAICHUR Faculty\nआईआईट\x00एच संकाय सपो\x00ट\x00ग आईआईआईट\x00 संकाय/\n28-34\nIITH Faculty Supporting IIIT Raichur\n35-36 आईआईट\x00एच संकाय सपो\x00ट\

In [14]:
df = pd.DataFrame(data)
df.head()

page_number                                               text
0            0  2022 - 23\nवाषक तवेदन\nAnnual Report\nआईआई...
1            1  पृ/ Page 2\nWinning Entry: Eco-Friendly\nGane...
2            2  पृ/ Page 3\n/ Contents\nअनुमणका\n4-5 परचय ...
3            3  पृ/ Page 4\nपरचय\nभारतीय सूचना ौोिगक सं ...
4            4  पृ/ Page 5\nIntroduction\nThe Indian Institut...

# Vector Spaces
- Turn the docs into vectors
- Term-document matrix
 - rows: documents
 - columns: words/tokens

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
#TF-IDF stands for Term Frequency Inverse Document Frequency of records. It can be defined as the calculation of how relevant a word in a series or corpus is to a text

In [16]:
cv = TfidfVectorizer(min_df=3, stop_words='english')
X = cv.fit_transform(df.text)

cv -> count vectorizer
X -> term-document matrix

In [17]:
names = cv.get_feature_names_out() # Token stored
df_docs = pd.DataFrame(X.toarray(), columns=names) 
# df_docs.round(2)
df_docs.head()

01   02   03   04   07   08   09   10  100        11  ...  सहय   हक  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.075973  ...  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  ...  0.0  0.0   

         हत  हतर   हद   हन   हम  हमन        हर   हल  
0  0.000000  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  
1  0.000000  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  
2  0.000000  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  
3  0.041646  0.0  0.0  0.0  0.0  0.0  0.035382  0.0  
4  0.000000  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  

[5 rows x 903 columns]

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(stop_words='english', min_df=10)
X = cv.fit_transform(df.text)

In [19]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3618 stored elements and shape (103, 177)>

In [20]:
query = "what is placement status of students"
q = cv.transform([query])
q.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]])

In [21]:
X.dot(q.T).todense() # this is the cosine similarity b/w query matrics and data matrics

matrix([[0.        ],
        [0.        ],
        [0.07329223],
        [0.        ],
        [0.03891134],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.04117909],
        [0.05044912],
        [0.68737788],
        [0.        ],
        [0.03246535],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06687063],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.06979571],
        [0.        ],
        [0.52345494],
        [0.        ],
        [0.67258552],
        [0.        ],
        [0.15243041],
        [0.        ],
        [0.07946207],
        [0.        ],
        [0

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
score = cosine_similarity(X, q).flatten()
score

array([0.        , 0.        , 0.07329223, 0.        , 0.03891134,
       0.        , 0.        , 0.        , 0.04117909, 0.05044912,
       0.68737788, 0.        , 0.03246535, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06687063, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.06979571, 0.        , 0.52345494, 0.        , 0.67258552,
       0.        , 0.15243041, 0.        , 0.07946207, 0.        ,
       0.        , 0.69998412, 0.        , 0.31627455, 0.        ,
       0.54450483, 0.        , 0.30618583, 0.        , 0.32214364,
       0.        , 0.21670208, 0.16713529, 0.20223687, 0.10107399,
       0.0611597 , 0.17874933, 0.1575567 , 0.09812423, 0.        ,
       0.        , 0.14332316, 0.        , 0.06681426, 0.05726538,
       0.08607106, 0.        , 0.17077733, 0.        , 0.     

In [24]:
import numpy as np

idx = np.argsort(score)[-5:]

In [25]:
results = df.iloc[idx]

In [26]:
results.to_dict(orient="records")

[{'page_number': 37,
  'text': 'पृ\x00/ Page 38\nAcademic Report\nIIIT Raichur is proud to announce that the first batch of students are going to\ngraduate from the institution and all the graduating students receive their degrees\nBTech in Computer Science and Engineering and BTech in Computer Science and\nEngineering (Honors) in the first convocation to be held.\nA total of 24 students successfully completed all the requirements for the award\nof degree BTech. Three students have yet to complete the requirements and are\nlikely to complete by the next semester. A detailed students list is given below:\nRoll No.\nS.No Name\n1 ABHISHEK SAHOO CS19B1001\n2 ADITYA AGRAWAL CS19B1003\n3 ANANYA MANTRAVADI CS19B1004\n4 BALIJA SUBHA SREE CS19B1005\n5 BONAMUKKALA VAMSI KRISHNA REDDY CS19B1006\n6 DEEPAK SAI PERISETLA CS19B1007\n7 DOSAWADA ROHITH CS19B1008 Honors Degree\n8 DUDDUVARI GANGADHAR CS19B1009\n9 DYAPA UDAY KUMAR REDDY CS19B1010\n10 ILLA SAI DEEPIKA CS19B1011\n11 JATIN SACHDEVA CS19B1013

In [27]:
from sklearn.decomposition import TruncatedSVD
# to compress the matric and reduce the dimentionality


In [28]:
X


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3618 stored elements and shape (103, 177)>

In [29]:
svd = TruncatedSVD(n_components=16) # compressed into 16 components
X_emb = svd.fit_transform(X)

In [30]:
X_emb[0]

array([ 0.32230068, -0.37224458, -0.27278307, -0.23558111, -0.24848206,
       -0.35631046,  0.17867175, -0.17866162,  0.18355342,  0.20259297,
        0.04540271, -0.27625463,  0.0443678 , -0.18525372, -0.09248741,
        0.06421941])

In [31]:
query = "what is placement status of students"
Q = cv.transform([query])
q_emb = svd.transform(Q)
q_emb[0]

array([ 0.15358123, -0.20617586, -0.21566976,  0.36025854, -0.15424908,
        0.08869823, -0.40278424,  0.04078363, -0.23951108, -0.17552855,
        0.21890553, -0.15661893,  0.11263506,  0.14091185, -0.12465503,
       -0.13154905])

In [32]:
score = cosine_similarity(X_emb, q_emb).flatten()
idx = np.argsort(score)[-5:]
list(df.iloc[idx].text)

['पृ\x00/ Page 38\nAcademic Report\nIIIT Raichur is proud to announce that the first batch of students are going to\ngraduate from the institution and all the graduating students receive their degrees\nBTech in Computer Science and Engineering and BTech in Computer Science and\nEngineering (Honors) in the first convocation to be held.\nA total of 24 students successfully completed all the requirements for the award\nof degree BTech. Three students have yet to complete the requirements and are\nlikely to complete by the next semester. A detailed students list is given below:\nRoll No.\nS.No Name\n1 ABHISHEK SAHOO CS19B1001\n2 ADITYA AGRAWAL CS19B1003\n3 ANANYA MANTRAVADI CS19B1004\n4 BALIJA SUBHA SREE CS19B1005\n5 BONAMUKKALA VAMSI KRISHNA REDDY CS19B1006\n6 DEEPAK SAI PERISETLA CS19B1007\n7 DOSAWADA ROHITH CS19B1008 Honors Degree\n8 DUDDUVARI GANGADHAR CS19B1009\n9 DYAPA UDAY KUMAR REDDY CS19B1010\n10 ILLA SAI DEEPIKA CS19B1011\n11 JATIN SACHDEVA CS19B1013\n12 KANCHARLA GOWTHAM CS19B10

In [33]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=16)
W = nmf.fit_transform(X)
W[0]

array([0.        , 0.        , 0.        , 0.0075988 , 0.16229526,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.30287285, 0.        , 0.15356686, 0.        ,
       0.        ])

In [34]:
Q = cv.transform([query])
q_emb = nmf.transform(Q)
q_emb[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.44799296, 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [35]:
score = cosine_similarity(W, q_emb).flatten()
idx = np.argsort(score)[-5:]
df.iloc[idx].text

39    पृ/ Page 40\n/Placements\nेसमट\nAt IIITR, o...
10    पृ/ Page 11\nReport of Director IIIT Raichur\...
48    पृ/ Page 49\n/ Hostels\nहॉटल\nTungabhadra Ho...
50    पृ/ Page 51\n/ Hostels\nहॉटल\nFederal Hostel...
46    पृ/ Page 47\n/ Hostels\nहॉटल\nIIIT Raichur i...
Name: text, dtype: object